# Generated by Django 4.1 on 2023-06-26 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='time_slot',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.classslot', verbose_name='Class slot'),
        ),
    ]
