# Generated by Django 4.1.7 on 2023-06-02 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educator',
            options={'verbose_name': 'Educator', 'verbose_name_plural': 'Educators'},
        ),
        migrations.AlterField(
            model_name='coursetaken',
            name='class_slot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.classslot', verbose_name='Class slot'),
        ),
        migrations.AlterField(
            model_name='coursetaken',
            name='classroom',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.classroom', verbose_name='Classroom'),
        ),
        migrations.AlterField(
            model_name='coursetaken',
            name='faculty',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.educator', verbose_name='Faculty Name'),
        ),
        migrations.AlterField(
            model_name='coursetaken',
            name='section',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.course', verbose_name='Course Section'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='total_credit',
            field=models.FloatField(default=0, verbose_name='Number of credit taken'),
        ),
    ]
