# Generated by Django 4.1.7 on 2023-06-24 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='classroom',
            field=models.OneToOneField(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='api.classroom', verbose_name='Classroom'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='faculty',
            field=models.OneToOneField(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='api.faculty', verbose_name='Faculty taking the class'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='time_slot',
            field=models.OneToOneField(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='api.classslot', verbose_name='Class slot'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='section',
            name='course',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.course', verbose_name='Course Name'),
        ),
        migrations.DeleteModel(
            name='CourseTaken',
        ),
    ]
