# Generated by Django 4.1.7 on 2023-06-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_section_classroom_section_faculty_section_time_slot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Classroom Avaibility'),
        ),
    ]
