# Generated by Django 4.1.7 on 2023-06-23 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_course_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='building',
            field=models.CharField(choices=[('SAC', 'South Academic Buidling'), ('NAC', 'North Academic Buidling'), ('LIB', 'Library Building'), ('ADMIN', 'Admin Building')], max_length=10, verbose_name='academic building abbbrebiation'),
        ),
    ]
