# Generated by Django 4.1.7 on 2023-06-24 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_section_faculty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='building',
        ),
        migrations.AlterField(
            model_name='classroom',
            name='roomNo',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='classroom number'),
        ),
    ]
